language: en
dictionaries:
  - lorem-ipsum
words:
  - ABAC
  - actiondefinition
  - actionname
  - adminsecret
  - adminsecretkey
  - Aegg
  - aggr
  - aggregateobject
  - aggregateorderby
  - aggregationexp
  - agtestdb
  - aiven
  - Aiven
  - allowlistscope
  - alloydb
  - ametist
  - Amii
  - ANBA
  - andexp
  - Anjela
  - apihasura
  - apilimitoption
  - apilimits
  - apollofederationconfig
  - apollographql
  - appendargexp
  - applicationjson
  - ARAA
  - arrrelusing
  - arrrelusingfkeyon
  - arrrelusingmanualmapping
  - asdict
  - atleast
  - autocompleting
  - autoeventtriggercleanupconfig
  - autoincrementing
  - averylongpasswordstring
  - Aviv
  - awsvpc
  - Aytlc
  - azurecontainer
  - Barebones
  - Beltran
  - bengaluru
  - Bengaluru
  - Berti
  - Bggr
  - Bgkqhki
  - bigquerycomputedfielddefinition
  - bigqueryconfiguration
  - bigqueryfunctionname
  - bigquerytablename
  - bigserial
  - Blogposts
  - Blyton
  - bodytransform
  - boilerplates
  - Boilerplates
  - boolexp
  - BQYDK
  - bruteforce
  - Byauthor
  - bytea
  - Caddyfile
  - castexp
  - cffi
  - cffi's
  - cgte
  - citus
  - Citus
  - Citus’s
  - classmethod
  - Clickjacking
  - cloudsql
  - clte
  - cockroachdb
  - codegen
  - Codegen
  - CODEGEN
  - Coelho
  - collab
  - collectionname
  - collectionquery
  - colocated
  - Colocation
  - columnconfig
  - columnconfigvalue
  - columnexp
  - columnpresetexp
  - commmand
  - computedfielddefinition
  - computedfieldname
  - conflictclause
  - connectionobject
  - Contenful
  - covar
  - CQYDVQQG
  - CREATEROLE
  - cremet
  - customcolumnnames
  - customrootfield
  - dabba
  - DABBA
  - Datacenter
  - dataclass
  - Dataclass
  - dataclasses
  - datasource
  - Dbar
  - DBCOMPATIBILITY
  - dbname
  - Dbname
  - Ddtdtgb
  - deleteatpathargexp
  - deleteelemargexp
  - deletekeyargexp
  - deletepermission
  - distinctonexp
  - DMARC
  - Dockerhub
  - domainname
  - dont
  - Drona
  - elephantsql
  - endpointdef
  - endpointmethods
  - endpointurl
  - enterprisedb
  - enumvalue
  - envfile
  - EPSG
  - eventtriggercolumns
  - eventtriggerqualifier
  - existsexp
  - exploitability
  - fargate
  - Fargate
  - FARGATE
  - Fbaz
  - fdsa
  - Ffoo
  - fkey
  - Flore
  - formencoded
  - fromenv
  - fulltext
  - functionname
  - gcloud
  - GCNDG
  - geommin
  - getenv
  - Gett
  - Gjxot
  - graphiql
  - GraphiQL
  - GraphiQLIDE
  - graphqlname
  - graphqltype
  - graphqurl
  - Gridsome
  - GRTD
  - hadr
  - Hadr
  - hadrenabled
  - hasher
  - Hasher
  - hasura
  - Hasura
  - Hasura's
  - hasuradb
  - hasurauser
  - headerfromenv
  - headerfromvalue
  - headerkey
  - headervalue
  - healthz
  - Healthz
  - herokou
  - Heyy
  - Heyyy
  - hodor
  - Hodor
  - Hwrd
  - hyperscale
  - Hyperscale
  - ICXV
  - IEMDAT
  - Iiwg
  - Iiwia
  - Iiwibm
  - Ijox
  - Ikpva
  - ilike
  - ILIKE
  - Imperva
  - Inaj
  - incargexp
  - inet
  - inmemory
  - inputargument
  - inputarguments
  - inputobject
  - inputobjectfield
  - inputobjects
  - inputobjecttype
  - insertorder
  - insertpermission
  - ipam
  - iregex
  - isactive
  - jdbc
  - JDBC
  - JERTEYMBYGA
  - jondoe
  - jsonify
  - jumpstart
  - jwks
  - JWKS
  - JWTs
  - Kamila
  - Karnataka
  - Koramangala
  - koyeb
  - Koyeb
  - kriti
  - Kriti
  - Kriti's
  - labl
  - libpq
  - lifecycles
  - livequery
  - loadbalancer
  - lquery
  - lseg
  - ltree
  - ltxtquery
  - Lyndsay
  - macaddr
  - MAUG
  - maxage
  - maxdepth
  - MAXVALUE
  - Memorystore
  - metadataoperator
  - MIIB
  - MINVALUE
  - MITM
  - mssqlconfiguration
  - mssqlpoolsettings
  - mssqlsourceconnectioninfo
  - multirole
  - multistep
  - mutationresponse
  - myaccount
  - myadminsecretkey
  - myapp
  - mybool
  - mydb
  - mydomain
  - myorganization
  - myquery
  - myrole
  - myschema
  - mysecretkey
  - mysecretpassword
  - myusername
  - myvalue
  - mywh
  - N'tcp
  - namex
  - nband
  - NCHAR
  - newrerlic
  - nextjs
  - nextval
  - nhost
  - Nhost
  - nilike
  - Ninnetta
  - niregex
  - nlike
  - nljy
  - noninteractive
  - notexp
  - nregex
  - nsimilar
  - Nuxt
  - nvarchar
  - NVARCHAR
  - NVHREEID
  - NVHSUEDDAK
  - objectfield
  - objectrelationship
  - objecttype
  - objrelusing
  - objrelusingchoice
  - objrelusingmanualmapping
  - ODBC
  - OIDC
  - olap
  - oltp
  - openapi
  - OPENJSON
  - opentelemetry
  - Opentelemetry
  - operationspec
  - opname
  - optimise
  - optout
  - orderbyenum
  - orderbyexp
  - orexp
  - outputed
  - overridable
  - pageinfo
  - paginationexp
  - Paperform
  - Paulo
  - payg
  - pede
  - peerings
  - Peerings
  - permessage
  - pganalyze
  - pgcertsettings
  - pgcolumn
  - pgcolumntype
  - pgconfiguration
  - pgconnectionparameters
  - pgcrypto
  - pgdump
  - pgpoolsettings
  - pgsourceconnectioninfo
  - pincode
  - pkcolumnsargexp
  - pkey
  - plpgsql
  - plsql
  - Pooler
  - Postcondition
  - postgis
  - Postgis
  - Postgres
  - postgrespassword
  - PostgreSQL
  - Postrge
  - prefixlen
  - prependargexp
  - prepopulate
  - psql
  - pyjwt
  - Qbpa
  - qualifiedfunction
  - qualifiedtable
  - queryname
  - quickstart
  - Quickstart
  - Raichael
  - rast
  - ratelimitoption
  - ratelimitperroleoption
  - redirections
  - redishostname
  - refetches
  - regclass
  - relationshipname
  - relaydistinctonexp
  - relayorderbyexp
  - relaypaginationexp
  - relaywhereexp
  - rels
  - remotefield
  - remotefieldcustomization
  - remoterelationshipdefinition
  - remoterelationshipname
  - remoteschemacustomization
  - remoteschemadef
  - remoteschemaname
  - remoteschemapermission
  - remotetable
  - remotetypecustomization
  - replyto
  - reqs
  - requesttransformation
  - responsetransformation
  - RESTified
  - retryconf
  - retryconfst
  - Rickard
  - roadmap
  - Robben
  - rolename
  - rollbacked
  - ROOTCERT
  - rootfieldscustomization
  - sametable
  - sarahlewis
  - sastisfy
  - scalartype
  - secretpassword
  - selectpermission
  - sendgrid
  - SENDGRID
  - Sengrid
  - setargexp
  - SETOF
  - Shortcodes
  - signup
  - Signup
  - simpleobject
  - slowloris
  - smallint
  - smallserial
  - snowflakecomputing
  - sourcecustomization
  - sourcename
  - sourcetypecustomization
  - sqlag
  - sqlagent
  - sqlcmd
  - sqlcommenter
  - sqlnode
  - sqlservr
  - sslcert
  - sslkey
  - sslmode
  - sslpassword
  - sslrootcert
  - sslverify
  - SSRF
  - subnetabcd
  - Subquery
  - supabase
  - Supabase
  - sysdatabases
  - tableaggoporderby
  - tablename
  - tableorderby
  - tableselectcolumnenum
  - Tabnabbing
  - taboolexpblename
  - tempdb
  - templateengine
  - templating
  - Templating
  - testsuite
  - Tfsdfds
  - Tgfkj
  - TGKD
  - Thanos
  - themable
  - timescaledb
  - timestamptz
  - Timestamptz
  - timetz
  - Timetz
  - titlesonly
  - toctree
  - todos
  - Todos
  - tokai
  - toschemarelationshipdefinition
  - tosourcerelationshipdefinition
  - tracecontext
  - traefik
  - Traefik
  - transfomation
  - transformheaders
  - trgm
  - triggerlogcleanupsources
  - triggername
  - trueexp
  - tsquery
  - tsvector
  - TTBLMAs
  - txid
  - TXISO
  - txqueuelen
  - typenames
  - ujdh
  - unioned
  - UNIQUEIDENTIFIER
  - unnest
  - UNNEST
  - updatepermission
  - uppercased
  - Uppercased
  - upsert
  - Upsert
  - upsertable
  - upserting
  - upserts
  - urlencode
  - urlfromenv
  - urschris
  - userid
  - usernamex
  - varbit
  - varchar
  - VARCHAR
  - Vfjp
  - Vgyo
  - Vuetify
  - Vuex
  - webhookurl
  - websockets
  - Websockets
  - Werkzeug
  - westus
  - whereargexp
  - whereexp
  - XGET
  - Xhhb
  - xurl
  - XVCJ
  - yabba
  - YABBA
  - Ymxp
  - yugabyte
  - Yugabyte
  - Yywg
  - Zuckerberg
